package ajman.shayan.joisty.models.report.tables

const val AMOUNT = "AMOUNT"
const val AREA_LOAD = "AREA_LOAD"
const val AREA_SECTION = "AREA_SECTION"
const val COMPONENT = "COMPONENT"
const val HEIGHT = "HEIGHT"
const val LENGTH = "LENGTH"
const val LENGTH_RATIO = "LENGTH_RATIO"
const val PRICE = "PRICE"
const val PRICE_PER_UNIT = "PRICE_PER_UNIT"
const val SPECIFIC_WEIGHT = "SPECIFIC_WEIGHT"
const val THICKNESS = "THICKNESS"
const val UNIT = "UNIT"
const val VOLUME = "VOLUME"
const val WEIGHT = "WEIGHT"
const val WIDTH_RATIO = "WIDTH_RATIO"